management.endpoints.web.exposure.include = *
management.info.env.enabled = true

spring.application.name=bill_payment

info.app.name = Bill Payment transfer project
info.app.description = a backend money transfer using spring boot

spring.datasource.url=jdbc:postgresql://localhost:5432/bill_payment
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.banner-mode = off

server.servlet.context-path=/api